import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/sidebar";
import { Separator } from "@/components/ui/separator";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { getSession } from "@/lib/auth/get-session";
import { AuthProvider } from "@/components/auth/auth-provider";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authPromise = getSession();

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
    >
      <body>
        <AuthProvider authPromise={authPromise}>
          <ThemeProvider attribute="class">
            <SidebarProvider>
                <AppSidebar />
              <div className="min-h-full flex flex-col flex-1">
                <nav>
                  <div className="container mx-auto p-4 flex gap-2 items-center">
                    <SidebarTrigger />
                    <div className="flex-1" />
                    <ModeToggle />
                  </div>
                </nav>
                <Separator />
                <main className="flex-1 flex flex-col">
                  <div className="container mx-auto p-4 flex-1">{children}</div>
                </main>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
