import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/sidebar";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { getSession } from "@/lib/auth/get-session";
import { AuthProvider } from "@/components/auth/auth-provider";
import { CSSProperties, Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";
import { Badge } from "@/components/ui/badge";
import { Rocket } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authPromise = getSession();

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
    >
      <body
        className="dark"
        style={{ "--custom": "color-mix(in oklab, var(--primary) 25%, transparent)" } as CSSProperties}
      >
        <AuthProvider authPromise={authPromise}>
          <SidebarProvider>
            <Suspense>
              <AppSidebar />
            </Suspense>
            <div className="min-h-full flex flex-col flex-1">
              <nav>
                <div className="container mx-auto p-4 flex gap-2 items-center">
                  <SidebarTrigger />
                  <div className="flex-1" />
                  <Suspense fallback={<Skeleton className="size-8" />}>
                    <ModeToggle />
                  </Suspense>
                </div>
              </nav>
              <Separator />
              <main className="flex-1 flex flex-col">
                <div className="container mx-auto p-4 flex-1">{children}</div>
              </main>
              <Separator />
              <footer>
                <div className="container mx-auto p-4 flex gap-2 items-center">
                  <div className="flex-1" />
                  <Badge variant="secondary">
                    {" "}
                    <Rocket /> Powered by Menelaus
                  </Badge>
                </div>
              </footer>
            </div>
          </SidebarProvider>
        </AuthProvider>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
